name: Android Build & Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build APK
      run: ./gradlew assembleRelease

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: andriod/build/outputs/apk/release/*.apk

  deploy:
    runs-on: ubuntu-latest

    needs: release

    steps:
    - name: Download Release Artifact
      uses: actions/download-artifact@v2
      with:
        name: app-release
        path: app-release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app-release/*.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
