name: Build Android

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # Gradle Cache https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/checkout@v4
      - name: Set up JDK  17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # or 'adopt', depending on your preference
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Yarn Cache: https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Bundle *.aab & *.apk
        run: cd android && ./gradlew bundleRelease assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Aab
          path: android/app/build/outputs/bundle/release/app-release.aab
       # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
       # Upload APK
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing its ID to get the URL to upload the asset to
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive